export default {
    "data":{
       "userDoTestVersion":{
          "_id":"5da9f1908eb3387e8a838e98",
          "code":"2dbbaa",
          "testSet":{
             "_id":"5da9f1198eb3387e8a838e8d",
             "duration":30,
             "title":"Demo awesome test",
             "allowResumeAfterExit":true,
             "allowNext":true,
             "allowPrevious":true,
             "allowViewUserScore":true,
             "allowDoManyTimes":true,
             "showFullTest":false,
             "isTestTime":true,
             "chooseAvgScore":false,
             "reviewPermission":3
          },
          "bigQuestionList":[
             {
                "_id":"5da9dc92e045012bcd9243f3",
                "content":"{}",
                "image":null,
                "video":null,
                "duration":60,
                "timeOut":true,
                "smallQuestionList":[
                   {
                      "_id":"5da9dc92e045012bcd9243f5",
                      "question":"{\"blocks\":[{\"key\":\"2k4sn\",\"text\":\" When she was crossing the room, the night-nurse happened to notice an old lady …… to get out of bed. \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":1,
                      "choiceList":[
                         {
                            "_id":"5da9dc92e045012bcd9243f6",
                            "content":"{\"blocks\":[{\"key\":\"cjpgh\",\"text\":\" has tried \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":0,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9dc92e045012bcd9243f7",
                            "content":"{\"blocks\":[{\"key\":\"18dkb\",\"text\":\" to try \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":1,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9dc92e045012bcd9243f8",
                            "content":"{\"blocks\":[{\"key\":\"3qrud\",\"text\":\" trying \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":2,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9dc92e045012bcd9243f9",
                            "content":"{\"blocks\":[{\"key\":\"7mgl0\",\"text\":\" tried \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":3,
                            "isLeft":false,
                            "image":null
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null,
                         null,
                         null
                      ],
                      "userAnswer":null
                   }
                ]
             },
             {
                "_id":"5da9dd92e045012bcd9243fa",
                "content":"{}",
                "image":null,
                "video":null,
                "duration":60,
                "timeOut":false,
                "smallQuestionList":[
                   {
                      "_id":"5da9dd92e045012bcd9243fc",
                      "question":"{\"blocks\":[{\"key\":\"1ebi4\",\"text\":\"Kéo từ thích hợp vào chỗ trống\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{\"blocks\":[{\"key\":\"fg4if\",\"text\":\" There are many means of \\t to travel around the world and lots of people choose \\t. While it is true that travelling by the airplane has generated numerous benefits, there are a number of \\t put into \\t. \",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{},\"blankRanges\":[{\"offset\":25,\"order\":0},{\"offset\":80,\"order\":1},{\"offset\":187,\"order\":2},{\"offset\":198,\"order\":3}]},{\"key\":\"o3o4\",\"text\":\"To sum up, there is no doubt that while many \\t can be identified thanks to travelling by airplane, it will bring some unpleasant loss as a result. It is avisable to make a carefully \\t before booking flight tickets so that having a great travelling. \",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{},\"blankRanges\":[{\"offset\":45,\"order\":4},{\"offset\":182,\"order\":5}]}],\"entityMap\":{}}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":2,
                      "choiceList":[
                         {
                            "_id":"5da9dd92e045012bcd9243fd",
                            "content":"transport",
                            "order":0,
                            "isLeft":null,
                            "image":null
                         },
                         {
                            "_id":"5da9dd92e045012bcd9243fe",
                            "content":"airplane",
                            "order":1,
                            "isLeft":null,
                            "image":null
                         },
                         {
                            "_id":"5da9dd92e045012bcd924400",
                            "content":"consideration",
                            "order":3,
                            "isLeft":null,
                            "image":null
                         },
                         {
                            "_id":"5da9dd92e045012bcd9243ff",
                            "content":"disadvantages",
                            "order":2,
                            "isLeft":null,
                            "image":null
                         },
                         {
                            "_id":"5da9dd92e045012bcd924402",
                            "content":"decision",
                            "order":5,
                            "isLeft":null,
                            "image":null
                         },
                         {
                            "_id":"5da9dd92e045012bcd924401",
                            "content":"advantages",
                            "order":4,
                            "isLeft":null,
                            "image":null
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null,
                         null,
                         null,
                         null,
                         null
                      ],
                      "userAnswer":null
                   }
                ]
             },
             {
                "_id":"5da9de60e045012bcd924403",
                "content":"{}",
                "image":null,
                "video":null,
                "duration":60,
                "timeOut":false,
                "smallQuestionList":[
                   {
                      "_id":"5da9de60e045012bcd924405",
                      "question":"{\"blocks\":[{\"key\":\"cm66n\",\"text\":\"Nối các câu trả lời vào câu hỏi tương ứng\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":5,
                      "choiceList":[
                         {
                            "_id":"5da9de60e045012bcd924406",
                            "content":"{\"blocks\":[{\"key\":\"ct27\",\"text\":\"Where are you from?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":0,
                            "isLeft":true,
                            "image":null
                         },
                         {
                            "_id":"5da9de60e045012bcd92440a",
                            "content":"{\"blocks\":[{\"key\":\"3284f\",\"text\":\"I'm Anh\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":0,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9de60e045012bcd924407",
                            "content":"{\"blocks\":[{\"key\":\"7okrn\",\"text\":\"How are you?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":1,
                            "isLeft":true,
                            "image":null
                         },
                         {
                            "_id":"5da9de60e045012bcd92440b",
                            "content":"{\"blocks\":[{\"key\":\"148qt\",\"text\":\"I'm 30 years old\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":1,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9de60e045012bcd924408",
                            "content":"{\"blocks\":[{\"key\":\"g69b\",\"text\":\"How old are you?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":2,
                            "isLeft":true,
                            "image":null
                         },
                         {
                            "_id":"5da9de60e045012bcd92440c",
                            "content":"{\"blocks\":[{\"key\":\"37ecf\",\"text\":\"I'm from Vietnam\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":2,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9de60e045012bcd924409",
                            "content":"{\"blocks\":[{\"key\":\"3843t\",\"text\":\"What is your name?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":3,
                            "isLeft":true,
                            "image":null
                         },
                         {
                            "_id":"5da9de60e045012bcd92440d",
                            "content":"{\"blocks\":[{\"key\":\"45rdp\",\"text\":\"I'm good\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":3,
                            "isLeft":false,
                            "image":null
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null,
                         null,
                         null
                      ],
                      "userAnswer":null
                   }
                ]
             },
             {
                "_id":"5da9e0f4e045012bcd92440e",
                "content":"{}",
                "image":"https://res.cloudinary.com/awsteyouthvn/image/upload/f_auto,q_auto:eco/v1571414155/files/h7x0xeya6l9dbnetyng0.jpg",
                "video":null,
                "duration":25,
                "timeOut":false,
                "smallQuestionList":[
                   {
                      "_id":"5da9e0f4e045012bcd924410",
                      "question":"{\"blocks\":[{\"key\":\"46sva\",\"text\":\"How many people in the picture?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":1,
                      "choiceList":[
                         {
                            "_id":"5da9e0f4e045012bcd924411",
                            "content":"{\"blocks\":[{\"key\":\"9aac9\",\"text\":\"4\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":0,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9e0f4e045012bcd924412",
                            "content":"{\"blocks\":[{\"key\":\"6r7s3\",\"text\":\"5\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":1,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da9e0f4e045012bcd924413",
                            "content":"{\"blocks\":[{\"key\":\"b7atn\",\"text\":\"6\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":2,
                            "isLeft":false,
                            "image":null
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null,
                         null
                      ],
                      "userAnswer":null
                   },
                   {
                      "_id":"5da9e0f4e045012bcd924414",
                      "question":"{\"blocks\":[{\"key\":\"8vhja\",\"text\":\"Điền từ thích hợp vào câu sau\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{\"blocks\":[{\"key\":\"bnqln\",\"text\":\"They are sitting on the \\t. They \\t smiling and look very happy.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{},\"blankRanges\":[{\"offset\":24,\"order\":0},{\"offset\":32,\"order\":1}]}],\"entityMap\":{}}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":4,
                      "choiceList":[
                         {
                            "_id":"5da9e0f4e045012bcd924415",
                            "content":"grass",
                            "order":0,
                            "isLeft":null,
                            "image":null
                         },
                         {
                            "_id":"5da9e0f4e045012bcd924416",
                            "content":"are",
                            "order":1,
                            "isLeft":null,
                            "image":null
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null
                      ],
                      "userAnswer":null
                   },
                   {
                      "_id":"5da9e0f4e045012bcd924417",
                      "question":"{\"blocks\":[{\"key\":\"fs6tr\",\"text\":\"Mô tả bức tranh trên (khoảng 200 từ)\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":3,
                      "choiceList":[
 
                      ],
                      "userChoiceList":null,
                      "userAnswer":null
                   }
                ]
             },
             {
                "_id":"5da9e1b8e045012bcd924418",
                "content":"{}",
                "image":null,
                "video":null,
                "duration":5,
                "timeOut":false,
                "smallQuestionList":[
                   {
                      "_id":"5e4b576ae1495d31521b30c8",
                      "question":"{\"blocks\":[{\"key\":\"36nge\",\"text\":\"Sắp xếp các câu sau để thành một đoạn văn hoàn chỉnh\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":6,
                      "choiceList":[
                         {
                            "_id":"5e4b576ae1495d31521b30cc",
                            "content":"{\"blocks\":[{\"key\":\"vs56\",\"text\":\"  For instance, it will take about 18 hours to arrive form Danang to Ho Chi Minh by train, however, it will take only 2 hours by plane.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":0,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5e4b576ae1495d31521b30c9",
                            "content":"{\"blocks\":[{\"key\":\"cbrco\",\"text\":\" On one hand, the merits of travelling by plane cannot be questionable.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":1,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5e4b576ae1495d31521b30cb",
                            "content":"{\"blocks\":[{\"key\":\"3m6k4\",\"text\":\"  This is because that the fastest way of travel would be plane.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":2,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5e4b576ae1495d31521b30cd",
                            "content":"{\"blocks\":[{\"key\":\"9if7t\",\"text\":\" As a result, air travel will shorten time. In addition, aircrafts have made it possible to travel to any worldwide regions.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":3,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5e4b576ae1495d31521b30ca",
                            "content":"{\"blocks\":[{\"key\":\"1l8m7\",\"text\":\" In the first place, travelling by air enables passengers to reach their destinations in a short time.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":4,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5e4b576ae1495d31521b30ce",
                            "content":"{\"blocks\":[{\"key\":\"8rcbp\",\"text\":\"The reason is that airplane might be one of the most mordenest transportation recently.  \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":5,
                            "isLeft":false,
                            "image":null
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null,
                         null,
                         null,
                         null,
                         null
                      ],
                      "userAnswer":null
                   }
                ]
             },
             {
                "_id":"5da2ec59e045012bcd924382",
                "content":"{}",
                "image":null,
                "video":null,
                "duration":5,
                "timeOut":false,
                "smallQuestionList":[
                   {
                      "_id":"5da2ec59e045012bcd924384",
                      "question":"{\"blocks\":[{\"key\":\"8mdu1\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{}",
                      "image":"https://res.cloudinary.com/awsteyouthvn/image/upload/f_auto,q_auto:eco/v1570958312/files/zqydriws4o954rprxxqd.jpg",
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":1,
                      "choiceList":[
                         {
                            "_id":"5da2ec59e045012bcd924385",
                            "content":"{}",
                            "order":0,
                            "isLeft":false,
                            "image":"https://res.cloudinary.com/awsteyouthvn/image/upload/f_auto,q_auto:eco/v1570958338/files/fm4oaypzjnxhblbzhflp.jpg"
                         },
                         {
                            "_id":"5da2ec59e045012bcd924386",
                            "content":"{}",
                            "order":1,
                            "isLeft":false,
                            "image":"https://res.cloudinary.com/awsteyouthvn/image/upload/f_auto,q_auto:eco/v1570958346/files/dp22idnnxhovfhikwecb.jpg"
                         },
                         {
                            "_id":"5da2ec59e045012bcd924387",
                            "content":"{}",
                            "order":2,
                            "isLeft":false,
                            "image":"https://res.cloudinary.com/awsteyouthvn/image/upload/f_auto,q_auto:eco/v1570958352/files/bzw4p3jgplgvjgorkixi.jpg"
                         },
                         {
                            "_id":"5da2ec59e045012bcd924388",
                            "content":"{}",
                            "order":3,
                            "isLeft":false,
                            "image":"https://res.cloudinary.com/awsteyouthvn/image/upload/f_auto,q_auto:eco/v1570958358/files/vzqyppncsaypxgbidkoi.jpg"
                         },
                         {
                            "_id":"5da2ec59e045012bcd924389",
                            "content":"{}",
                            "order":4,
                            "isLeft":false,
                            "image":"https://res.cloudinary.com/awsteyouthvn/image/upload/f_auto,q_auto:eco/v1570958366/files/qfsownrpcg7guzswclpu.jpg"
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null,
                         null,
                         null,
                         null
                      ],
                      "userAnswer":null
                   }
                ]
             },
             {
                "_id":"5da2ea37e045012bcd924377",
                "content":"{}",
                "image":null,
                "video":null,
                "duration":5,
                "timeOut":false,
                "smallQuestionList":[
                   {
                      "_id":"5da2ea37e045012bcd924379",
                      "question":"{\"blocks\":[{\"key\":\"arckn\",\"text\":\"Bạn thuộc độ tuổi nào?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                      "content":"{}",
                      "image":null,
                      "video":null,
                      "file":null,
                      "duration":null,
                      "order":0,
                      "multiAnswer":false,
                      "randomChoice":false,
                      "maximumWords":0,
                      "questionType":1,
                      "choiceList":[
                         {
                            "_id":"5da2ea37e045012bcd92437a",
                            "content":"{\"blocks\":[{\"key\":\"4jni9\",\"text\":\"18-25\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":0,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da2ea37e045012bcd92437b",
                            "content":"{\"blocks\":[{\"key\":\"ae04h\",\"text\":\"26-30\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":1,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da2ea37e045012bcd92437c",
                            "content":"{\"blocks\":[{\"key\":\"2nfo5\",\"text\":\"31-35\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":2,
                            "isLeft":false,
                            "image":null
                         },
                         {
                            "_id":"5da2ea37e045012bcd92437d",
                            "content":"{\"blocks\":[{\"key\":\"4l1r3\",\"text\":\"> 35\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
                            "order":3,
                            "isLeft":false,
                            "image":null
                         }
                      ],
                      "userChoiceList":[
                         null,
                         null,
                         null,
                         null
                      ],
                      "userAnswer":null
                   }
                ]
             }
          ],
          "testSession":null,
          "pause":false,
          "doingTest":null,
          "continueDoing":false,
          "requirePassword":null
       }
    }
 };